### ISSUE TITLE
logbook command returns error

### ISSUE THREAD

**Issue by lukew3** [lukew3/pythonlogbook#8]
When `logbook` is ran after install, a log is successfully created but this error message is shown after normal output:
```
Traceback (most recent call last):
  File "/usr/bin/logbook", line 11, in <module>
    load_entry_point('logbook==1.2', 'console_scripts', 'logbook')()
TypeError: 'module' object is not callable
```

**Comment by lukew3** [comment]
Ubuntu generates a crash report that says, 
```
logbook crashed with TypeError in __main__: 'module' object is not callable
```
The traceback is:
```
Traceback(most recent call last):
 File "/usr/bin/logbook", line 11, in <module>
  load_entry_point('logbook==1.0.0', 'console_scripts', 'logbook')()
TypeError: 'module' object is not callable
```

**Comment by lukew3** [comment]
console_scripts needed to be `newlog=pythonlogbook.addentry:main`  and main function needed to be added to addentry.py. Old console_scripts command was `newlog=pythonlogbook.addentry`
